const marketplaceAbi = [
  { type: "constructor", stateMutability: "nonpayable", inputs: [] },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        type: "address",
        name: "previousOwner",
        internalType: "address",
        indexed: true,
      },
      {
        type: "address",
        name: "newOwner",
        internalType: "address",
        indexed: true,
      },
    ],
    anonymous: false,
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "KolorLandNFTAddress",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "addOffsetsEmissionsOfBuyer",
    inputs: [
      { type: "uint256", name: "tokenId", internalType: "uint256" },
      { type: "uint256", name: "emissions", internalType: "uint256" },
      { type: "uint256", name: "vcuPrice", internalType: "uint256" },
      { type: "address", name: "account", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "addOffsetsEmmisionsOfLand",
    inputs: [
      { type: "uint256", name: "tokenId", internalType: "uint256" },
      { type: "uint256", name: "emissions", internalType: "uint256" },
      { type: "uint256", name: "vcuPrice", internalType: "uint256" },
      { type: "address", name: "account", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "authorize",
    inputs: [{ type: "address", name: "manager", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "getBalance",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "isAuthorized",
    inputs: [{ type: "address", name: "", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "payable",
    outputs: [],
    name: "offsetEmissions",
    inputs: [
      { type: "uint256", name: "tokenId", internalType: "uint256" },
      { type: "uint256", name: "emissions", internalType: "uint256" },
      { type: "uint256", name: "vcuPrice", internalType: "uint256" },
      { type: "address", name: "account", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "tuple",
        name: "",
        internalType: "struct OffsetEmission",
        components: [
          { type: "uint256", name: "vcuOffset", internalType: "uint256" },
          { type: "uint256", name: "offsetDate", internalType: "uint256" },
          { type: "uint256", name: "vcuPrice", internalType: "uint256" },
          { type: "uint256", name: "tokenId", internalType: "uint256" },
          { type: "address", name: "account", internalType: "address" },
        ],
      },
    ],
    name: "offsetInfo",
    inputs: [
      { type: "uint256", name: "offsetId", internalType: "uint256" },
      { type: "address", name: "account", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "tuple",
        name: "",
        internalType: "struct OffsetEmission",
        components: [
          { type: "uint256", name: "vcuOffset", internalType: "uint256" },
          { type: "uint256", name: "offsetDate", internalType: "uint256" },
          { type: "uint256", name: "vcuPrice", internalType: "uint256" },
          { type: "uint256", name: "tokenId", internalType: "uint256" },
          { type: "address", name: "account", internalType: "address" },
        ],
      },
    ],
    name: "offsetInfo",
    inputs: [
      { type: "uint256", name: "offsetId", internalType: "uint256" },
      { type: "uint256", name: "tokenId", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "uint256", name: "vcuOffset", internalType: "uint256" },
      { type: "uint256", name: "offsetDate", internalType: "uint256" },
      { type: "uint256", name: "vcuPrice", internalType: "uint256" },
      { type: "uint256", name: "tokenId", internalType: "uint256" },
      { type: "address", name: "account", internalType: "address" },
    ],
    name: "offsetsByAddress",
    inputs: [
      { type: "address", name: "", internalType: "address" },
      { type: "uint256", name: "", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "uint256", name: "vcuOffset", internalType: "uint256" },
      { type: "uint256", name: "offsetDate", internalType: "uint256" },
      { type: "uint256", name: "vcuPrice", internalType: "uint256" },
      { type: "uint256", name: "tokenId", internalType: "uint256" },
      { type: "address", name: "account", internalType: "address" },
    ],
    name: "offsetsByLand",
    inputs: [
      { type: "uint256", name: "", internalType: "uint256" },
      { type: "uint256", name: "", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "tuple[]",
        name: "",
        internalType: "struct OffsetEmission[]",
        components: [
          { type: "uint256", name: "vcuOffset", internalType: "uint256" },
          { type: "uint256", name: "offsetDate", internalType: "uint256" },
          { type: "uint256", name: "vcuPrice", internalType: "uint256" },
          { type: "uint256", name: "tokenId", internalType: "uint256" },
          { type: "address", name: "account", internalType: "address" },
        ],
      },
    ],
    name: "offsetsOf",
    inputs: [{ type: "uint256", name: "tokenId", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "tuple[]",
        name: "",
        internalType: "struct OffsetEmission[]",
        components: [
          { type: "uint256", name: "vcuOffset", internalType: "uint256" },
          { type: "uint256", name: "offsetDate", internalType: "uint256" },
          { type: "uint256", name: "vcuPrice", internalType: "uint256" },
          { type: "uint256", name: "tokenId", internalType: "uint256" },
          { type: "address", name: "account", internalType: "address" },
        ],
      },
    ],
    name: "offsetsOf",
    inputs: [{ type: "address", name: "account", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "bytes4", name: "", internalType: "bytes4" }],
    name: "onERC721Received",
    inputs: [
      { type: "address", name: "operator", internalType: "address" },
      { type: "address", name: "from", internalType: "address" },
      { type: "uint256", name: "tokenId", internalType: "uint256" },
      { type: "bytes", name: "data", internalType: "bytes" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "owner",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "removeLand",
    inputs: [{ type: "uint256", name: "tokenId", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "renounceOwnership",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setNFTAddress",
    inputs: [{ type: "address", name: "_NFTAddress", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "totalOffsetsOf",
    inputs: [{ type: "uint256", name: "tokenId", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "totalOffsetsOf",
    inputs: [{ type: "address", name: "account", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "totalOffsetsOfAddress",
    inputs: [{ type: "address", name: "", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "totalOffsetsOfLand",
    inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "transferOwnership",
    inputs: [{ type: "address", name: "newOwner", internalType: "address" }],
  },
];

module.exports = {
  marketplaceAbi,
};
